//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hosting
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string salt { get; set; }
    }
}
